flash more than one npk during netinstall
dvtirol/pynetinstall pull request #6
Opened 2024-07-11 17:00 UTC by rfdrake

This makes it so the plugin can return an array for get_files.  All the files are considered to be npk, except the last file which is considered to be the configuration.

2024-07-11 17:01 UTC, rfdrake commented
I verified to the best of my ability that this still works with the default plugin.  I don't think this will break backward compatibility, but feel free to test it and let me know if it needs changes.

2024-07-12 06:22 UTC, uedvt359 commented
Hi! thanks a lot - this is great! i wanted to have this feature for a while now, but couldn't expend the time. i'll have a look at your changes, but please be a bit patient with me :)

2024-07-12 06:57 UTC, uedvt359 requested changes
i had a quick cursory look and some suggestions and questions. once these are integrated, i'll do some testing on our infrastructure

2024-07-12 06:57 UTC, uedvt359 commented on pynetinstall/flash.py
> -            raise AbortFlashing("Plugin did not return RouterOS.")
I guess you removed this, because it looks superfluous with the check in verify_npk, but the plugin might return an error when called the second time.

2024-07-12 06:57 UTC, uedvt359 commented on pynetinstall/flash.py
> +        for npk in files[:-1]:
```suggestion
        *npks, rsc = self.plugin.get_files(self.info)
        if not all(npks):
            raise AbortFlashing("Plugin did not return RouterOS or an additional package.")
        for npk in npks:
```

(and removing line 354)

this has the benefit that if the plugin returns only a single-element tuple, we won't accidentally try to install the system.npk as a config file

2024-07-12 06:57 UTC, uedvt359 commented on pynetinstall/flash.py
> +        npk = self.plugin.get_files(info)[0]
```suggestion
        npk, *_ = self.plugin.get_files(info)
```

for consistency

2024-07-12 06:57 UTC, uedvt359 commented on pynetinstall/flash.py
> +        self.do(b"TERM\n")
why this change? i don't remember why we were doing this, so it's possible we had it wrong that whole time.

2024-07-12 14:57 UTC, rfdrake commented on pynetinstall/flash.py
> +        self.do(b"TERM\n")
I was going to take this out of the commit and forgot about it.   I took it out while troubleshooting.   This is probably incorrect because it's sending the message back to the mikrotik rather than sending it to the user.  I didn't see the original netinstall sending the message.

But it's probably harmless.  The mikrotik seems to ignore it.

2024-07-12 15:04 UTC, rfdrake commented on pynetinstall/flash.py
> -            raise AbortFlashing("Plugin did not return RouterOS.")
I think I removed this because of the nature of the loop I was using.  It comes down to me not knowing the pythonic way of doing these things, so I banged it together.

I think the new method you added with ```if not all(npks)``` looks good.

2024-07-29 08:38 UTC, uedvt359 commented on pynetinstall/flash.py
> -            raise AbortFlashing("Plugin did not return RouterOS.")
as far as i can see, this check is still missing from the current version, please add it back in. thanks!

2024-07-31 15:10 UTC, rfdrake commented on pynetinstall/flash.py
> -            raise AbortFlashing("Plugin did not return RouterOS.")
Wasn't the following code doing what "if npk is None" did?  
```
        if not all(npks):
            raise AbortFlashing("Plugin did not return RouterOS or an additional package is 'None'.")
```

I added it in 37a785344172c65a22d9235c73b2e4fe6b7bc88e.

2024-09-30 13:19 UTC, uedvt359 commented
sorry it took so long, but i finally got some time to test this out properly:

```
14:34:42 container,info,debug 2024-09-30 12:34:42,963 - [INFO ] -> Device found! mac=48:a9:8a:xx:xx:xx, model=RB5009UG+S+, arch=arm64
14:34:43 container,info,debug 2024-09-30 12:34:43,414 - [INFO ] -> Formatting 48:a9:8a:xx:xx:xx ...
14:35:20 container,info,debug 2024-09-30 12:35:20,755 - [INFO ] -> Uploading routeros-arm64-7.9.2.npk
14:35:28 container,info,debug 2024-09-30 12:35:28,734 - [INFO ] ->     routeros-arm64-7.9.2.npk: 10% 
14:35:37 container,info,debug 2024-09-30 12:35:37,113 - [INFO ] ->     routeros-arm64-7.9.2.npk: 20% 
14:35:45 container,info,debug 2024-09-30 12:35:45,509 - [INFO ] ->     routeros-arm64-7.9.2.npk: 30% 
14:35:53 container,info,debug 2024-09-30 12:35:53,885 - [INFO ] ->     routeros-arm64-7.9.2.npk: 40% 
14:36:02 container,info,debug 2024-09-30 12:36:02,287 - [INFO ] ->     routeros-arm64-7.9.2.npk: 50% 
14:36:10 container,info,debug 2024-09-30 12:36:10,644 - [INFO ] ->     routeros-arm64-7.9.2.npk: 60% 
14:36:19 container,info,debug 2024-09-30 12:36:19,027 - [INFO ] ->     routeros-arm64-7.9.2.npk: 70% 
14:36:27 container,info,debug 2024-09-30 12:36:27,408 - [INFO ] ->     routeros-arm64-7.9.2.npk: 80% 
14:36:35 container,info,debug 2024-09-30 12:36:35,843 - [INFO ] ->     routeros-arm64-7.9.2.npk: 90% 
14:36:44 container,info,debug 2024-09-30 12:36:44,248 - [INFO ] ->     routeros-arm64-7.9.2.npk: 100%
14:36:44 container,info,debug 2024-09-30 12:36:44,722 - [INFO ] -> Uploading zerotier-7.9.2-arm64.npk
14:36:45 container,info,debug 2024-09-30 12:36:45,191 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 10% 
14:36:45 container,info,debug 2024-09-30 12:36:45,698 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 20% 
14:36:46 container,info,debug 2024-09-30 12:36:46,189 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 30% 
14:36:46 container,info,debug 2024-09-30 12:36:46,679 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 40% 
14:36:47 container,info,debug 2024-09-30 12:36:47,188 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 50% 
14:36:47 container,info,debug 2024-09-30 12:36:47,690 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 60% 
14:36:48 container,info,debug 2024-09-30 12:36:48,179 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 70% 
14:36:48 container,info,debug 2024-09-30 12:36:48,690 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 80% 
14:36:49 container,info,debug 2024-09-30 12:36:49,187 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 90% 
14:36:49 container,info,debug 2024-09-30 12:36:49,684 - [INFO ] ->     zerotier-7.9.2-arm64.npk: 100%
14:36:49 container,info,debug 2024-09-30 12:36:49,760 - [INFO ] -> Uploading config.rsc
14:36:49 container,info,debug 2024-09-30 12:36:49,907 - [INFO ] -> 48:a9:8a:xx:xx:xx was successfully flashed.
14:36:49 container,info,debug 2024-09-30 12:36:49,915 - [INFO ] -> Waiting for devices...
```

as you can see, it works! :D it's not exposed in the simple plugin, but i'm using a company-internal one anyways.

2024-10-02 09:19 UTC, merged

2024-10-02 09:20 UTC, uedvt359 commented
thanks a lot! i'll work on an updated plugins/simple.py, then will likely make a new release.